.PHONY: clean

Colleen:
	python3 Colleen.py

Grace: 
	python3 Grace.py

Sully:
	python3 Sully.py

clean:
	@if [ -f "Grace_kid.py" ]; then rm Grace_kid.py; fi
	@if [ -f "Sully_4.py" ]; then rm Sully_4.py; fi
	@if [ -f "Sully_3.py" ]; then rm Sully_3.py; fi
	@if [ -f "Sully_2.py" ]; then rm Sully_2.py; fi
	@if [ -f "Sully_1.py" ]; then rm Sully_1.py; fi
	@if [ -f "Sully_0.py" ]; then rm Sully_0.py; fi
